firstpropgreet: 'this is what coming from properties greet  from config server'
comingpropr: 'proper and next propmix ${firstpropgreet}'
ly.list: one,two,three
d:
    conection:
        connectionstr: 'http://sdsarohit_____ from config server'
        usernam: ro
        passwo: txtnew
    host: 'testing host from config server'
    port: 123
    ls: one,two,three
